###
### A complete description of a Prefect Deployment for flow 'ingest-taxi'
###
name: ingest_taxi
description: |-
  Ingest the variant of the NYC Taxi dataset into the BQ Table with id.

  Stages partition data in a GCS Bucket before ingesting into BigQuery.

  Args:
      variant:
          Variant of thne NYC Taxi dataset to ingest.
      bucket:
          Name of the GCS Bucket used to stage ingested data.
      table_id:
          ID of the BigQuery table to ingesto data to, the format
          <PROJECT_ID>.<DATASET_ID>.<TABLE>
      partition:
          Date of partition to ingest. Since partitions are monthly sized,
          the day of month is disregarded if passed.
      truncate:
          Whether to truncate the table if it exists before writing.
version: 26c390f95092afbfc8a77f8b4a09c79b
# The work queue that will handle this deployment's runs
work_queue_name: default
tags: []
parameters:
  bucket: mrzzy-data-eng-zoomcamp-nytaxi
schedule: null
infra_overrides: {}

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: ingest-taxi
manifest_path: null
infrastructure:
  type: kubernetes-job
  env: {}
  labels: {}
  name: null
  command:
  - python
  - -m
  - prefect.engine
  image: us-west1-docker.pkg.dev/mrzzy-data-eng-zoomcamp/docker/prefect-nytaxi:latest
  namespace: default
  service_account_name: pipeline
  image_pull_policy: null
  cluster_config: null
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env: []
  customizations: []
  job_watch_timeout_seconds: 5
  pod_watch_timeout_seconds: 60
  stream_output: true
  _block_document_id: 2670cdaf-5b29-4d31-a7a1-85db67600746
  _block_document_name: data-proc-compute
  _is_anonymous: false
  _block_type_slug: kubernetes-job
storage:
  bucket_path: mrzzy-data-eng-zoomcamp-prefect
  service_account_info: '**********'
  project: null
  _block_document_id: 55043159-23ce-4d9c-a486-81907d5b43d6
  _block_document_name: prefect-storage
  _is_anonymous: false
  _block_type_slug: gcs
path: ''
entrypoint: src/taxi.py:ingest_taxi
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    variant:
      title: variant
      allOf:
      - $ref: '#/definitions/TaxiVariant'
    bucket:
      title: bucket
      type: string
    table_id:
      title: table_id
      type: string
    partition:
      title: partition
      type: string
      format: date
    truncate:
      title: truncate
      type: boolean
  required:
  - variant
  - bucket
  - table_id
  - partition
  - truncate
  definitions:
    TaxiVariant:
      title: TaxiVariant
      description: An enumeration.
      enum:
      - yellow
      - green
      - fhv
