###
### A complete description of a Prefect Deployment for flow 'ingest-taxi'
###
name: ingest_taxi
description: |-
  Ingest the variant of the NYC Taxi dataset into the BQ Table with id.

  Stages partition data in a GCS Bucket before ingesting into BigQuery.

  Args:
      variant:
          Variant of thne NYC Taxi dataset to ingest.
      bucket:
          Name of the GCS Bucket used to stage ingested data.
      table_id:
          ID of the BigQuery table to ingesto data to, the format
          <PROJECT_ID>.<DATASET_ID>.<TABLE>
      partition:
          Date of partition to ingest. Since partitions are monthly sized,
          the day of month & time component is disregarded if passed.
version: e5d00a3c0f7259fbc3e9ff059faeeb53
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: null
tags: 
  - nytaxi
parameters:
  bucket: mrzzy-data-eng-zoomcamp-nytaxi
schedule: null
is_schedule_active: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command: null
  stream_output: true
  working_dir: null
  block_type_slug: process
  _block_type_slug: process

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: ingest-taxi
manifest_path: null
storage:
  bucket_path: mrzzy-data-eng-zoomcamp-prefect
  service_account_info: null
  project: null
  _block_document_id: d49ca555-6225-4dc6-8984-19c58f18678b
  _block_document_name: prefect-storage
  _is_anonymous: false
  block_type_slug: gcs
  _block_type_slug: gcs
path: ''
entrypoint: src/taxi.py:ingest_taxi
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    variant:
      title: variant
      description: |2-

        Variant of thne NYC Taxi dataset to ingest.
      position: 0
      allOf:
      - $ref: '#/definitions/TaxiVariant'
    bucket:
      title: bucket
      description: |2-

        Name of the GCS Bucket used to stage ingested data.
      position: 1
      type: string
    table_id:
      title: table_id
      description: |2-

        ID of the BigQuery table to ingesto data to, the format
        <PROJECT_ID>.<DATASET_ID>.<TABLE>
      position: 2
      type: string
    partition:
      title: partition
      description: |2-

        Date of partition to ingest. Since partitions are monthly sized,
        the day of month & time component is disregarded if passed.
      position: 3
      type: string
      format: date-time
  required:
  - variant
  - bucket
  - table_id
  - partition
  definitions:
    TaxiVariant:
      title: TaxiVariant
      description: An enumeration.
      enum:
      - yellow
      - green
      - fhv
timestamp: '2023-02-09T22:23:31.945353+00:00'
