version: '3'
services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  migrate-db:
    build: .
    image: airflow
    command: db upgrade
    depends_on:
      - postgres
    env_file:
      - .env

  scheduler:
    image: airflow
    command: scheduler
    restart: on-failure
    depends_on:
      migrate-db:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /home/airflow/airflow-scheduler.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3

  webserver:
    image: airflow
    restart: on-failure
    command: webserver
    depends_on:
      migrate-db:
        condition: service_completed_successfully
      scheduler:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "80:8080"
    user: "${AIRFLOW_UID-0}"
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  postgres-db-volume:

